version: '3.8'

services:
  mt5-server:
    build: .
    container_name: mt5_headless
    restart: unless-stopped
    ports:
      - "5900:5900" # VNC port
    volumes:
      - ./mt5_data:/root/.wine # Persist MT5 configuration, EAs, and indicators
    environment:
      - DISPLAY=:99
      - SCREEN_SIZE=1280x1024x24